SkillsBook.com/SkillsBook.com/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using SkillsBook.Models.Models;
using SkillsBook.Models.DAL;
using SkillsBook.Models.ViewModel;
using System.Transactions;


namespace SkillsBook.com.Controllers
{
    public class PageController : Controller
    {
        private readonly UnitOfWork _unitOfWork = new UnitOfWork();
        public async Task<ActionResult> GetTags()
        {
            var tagsTrending = CacheImplementation.GetTrendingItems(Constants.TagsGeneral);
            var tagsAnnouncement = CacheImplementation.GetTrendingItems(Constants.TagsAnnouncement);
            await Task.WhenAll(tagsAnnouncement, tagsTrending);
            ViewBag.TagsGeneral = tagsTrending.Result;
            ViewBag.TagsAnnouncement = tagsAnnouncement.Result;
            return View();
        }

        [HttpGet]
        public ActionResult DisplayClassified(int classifiedId)
        {
            var model = _unitOfWork.ClassifiedRepository.GetById(classifiedId);
            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> DisplayPageByTags(string tagType, string cat, int size = 25)
        {
            var type = cat.Split('(')[0];
            IEnumerable<ThreadModel> tagsList;
            var query = "Select TOP " + Constants.BlocksizeInitialLoad + " * from " + Constants.SchemaName +
                        " [Threads]";
            switch (tagType)
            {
                case "TagsGeneral":
                    query = query + " Where TagsGeneral = " + "'" + type + "'" + " order by SubmittedOn desc";
                    tagsList = _unitOfWork.ThreadRepository.GetWithRawSql(query);
                    break;
                default:
                    query = query + " Where TagsAnnouncement = " + "'" + type + "'" + " order by SubmittedOn desc";
                    tagsList = _unitOfWork.ThreadRepository.GetWithRawSql(query);
                    break;
            }
            var allThreads = CacheImplementation.GetRecentThreads;
            var mostLiked = CacheImplementation.GetMostLikedThreads;
            var mostViewed = CacheImplementation.GetMostViewedThreads;
            var mostResponded = CacheImplementation.GetMostCommentedThreads;
            var trendingGeneral = CacheImplementation.GetTrendingItems(Constants.TagsGeneral);
            var trendingAnnouncement = CacheImplementation.GetTrendingItems(Constants.TagsAnnouncement);
            await Task.WhenAll(allThreads, mostLiked, mostViewed, mostResponded, trendingGeneral, trendingAnnouncement);
            ViewBag.MostLiked = mostLiked.Result;
            ViewBag.MostViewed = mostViewed.Result;
            ViewBag.MostResponded = mostResponded.Result;
            ViewBag.TrendingTagsGeneral = trendingGeneral.Result.Take(Constants.BlocksizeTrendingTags);
            ViewBag.TrendingTagsAnnouncement = trendingAnnouncement.Result.Take(Constants.BlocksizeTrendingTags);

            return View(tagsList);
        }

        [HttpGet]
        public ActionResult DisplayAllClassifieds(string type,int page = 1)
        {
            var classifieds = _unitOfWork.ClassifiedRepository.Get(x => x.ClassifiedCategory.Equals(type)).OrderByDescending(x=>x.LastUpdated);
            int totalCount = classifieds.Count();
            var offset = (page - 1) * Constants.BlocksizeMax;
           
            var model =
                classifieds.Skip((int)offset)
                       .Take(
                           (int)
                               (offset > Constants.BlocksizeMax
                                   ? offset - (offset - Constants.BlocksizeMax)
                                   : offset ==0 ? Constants.BlocksizeMax: offset));
            ViewBag.Cat = type;
            ViewData["CurrentPage"] = page;
            ViewData["TotalPages"] = ((totalCount - 1) / Constants.BlocksizeMax) + 1;
            return View(model);

        }

        [HttpGet]
        public ActionResult GetMorePostByCategory(string type, string category, int size = 25)
        {
            List<ThreadModel> posts = null;
            var repo = _unitOfWork.ThreadRepository;

            if (type == Constants.TagsGeneral)
            {
                posts = repo.Get(x => x.TagsGeneral.Equals(category))
                      .OrderByDescending(x => x.SubmittedOn)
                      .Skip(size)
                      .Take(size > Constants.BlocksizeInitialLoad ? size - (size - Constants.BlocksizeInitialLoad) : size)
                      .ToList();
            }
            else if (type == Constants.TagsAnnouncement)
            {
                posts = repo.Get(x => x.Announcement.Equals(category))
                      .OrderByDescending(x => x.SubmittedOn)
                      .Skip(size)
                      .Take(size > Constants.BlocksizeInitialLoad ? size - (size - Constants.BlocksizeInitialLoad) : size)
                      .ToList();
            }
            var count = posts.Count;
            ViewBag.Count = count;
            switch (count)
            {
                case 0:
                    return null;
            }
            return PartialView("Partial.PageByCategory", posts);
        }

        [HttpGet]
        public ActionResult AddThread()
        {
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult SubmitComment(string comment, int threadId)
        {
            var scope = new TransactionScope(TransactionScopeOption.RequiresNew, new TransactionOptions()
            {
                IsolationLevel = IsolationLevel.ReadCommitted
            });
            SkillsBook.Models.Models.ThreadModel threadRow = null;
            try
            {

                using (scope)
                {
                    var commentModel = new CommentModel
                    {
                        Thread_ThreadId = threadId,
                        CommentedBy = Request.Cookies["LogOnCookie"] == null
                            ? "Anonymous"
                            : Request.Cookies["LogOnCookie"].Values["username"],
                        CommentedOn = DateTime.Now,
                        IpAddress = GetIp(),
                        Browser = Request.Browser.Browser,
                        Comment = comment
                    };

                    _unitOfWork.CommentRepository.Insert(commentModel);
                    threadRow = _unitOfWork.ThreadRepository.GetById(threadId);
                    threadRow.Responses = threadRow.Responses + 1;
                    threadRow.LastUpdated = DateTime.Now;
                    _unitOfWork.ThreadRepository.Update(threadRow);
                    //CacheImplementation.UpdateCacheItem(CacheImplementation.RecentThreads, threadId, "Comments", null);
                   // CacheImplementation.UpdateCacheItem(CacheImplementation.MostCommentedThreads, threadId, "Comments", null);
                    CacheImplementation.ClearSpecificCacheObject(CacheImplementation.RecentThreads);
                    CacheImplementation.ClearSpecificCacheObject(CacheImplementation.MostCommentedThreads);

                    _unitOfWork.Save();
                    // notifyWatchers = true;
                    scope.Complete();
                    _unitOfWork.SendEmail(threadRow.Email, "Someone just commented in your thread",
                        "Dear " + threadRow.Username +
                        "<br /> Someone just commented on yout thread. <br /> Visit the link below to see the comment.<br />" +
                         Constants.Domain+"Page/DisplayThread?threadId="+threadRow.ThreadId+"<br /><br />"+
                        " With Best Regards <br />"+
                        Constants.Domain+"<br />"+Constants.Slogan);
                }
            }
            catch (Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                scope.Dispose();
                return Json(new { Result = "failed" });
            }
            return Json(new
            {
                Result = "success",
                TotalCount = threadRow.Responses,
                Comments = comment,
                CommentedBy = Request.Cookies["LogOnCookie"] == null
                    ? "Anonymous"
                    : Request.Cookies["LogOnCookie"].Values["username"],
                CommentedOn = DateTime.Now.ToLongDateString()
            });
        }



        public ActionResult GetMorePost(int size = 25)
        {
            var posts = _unitOfWork.ThreadRepository.Get(x => x.ThreadId > 0)
                         .OrderByDescending(x => x.LastUpdated)
                         .Skip(size)
                         .Take(size > Constants.BlocksizeInitialLoad ? size - (size - Constants.BlocksizeInitialLoad) : size)
                         .ToList();
            switch (posts.Count)
            {
                case 0:
                    return null;
            }
            return PartialView("Partial.GetMorePost", posts);

        }

        public ActionResult GetMorePostByUser(string username, int size = 15)
        {
            var posts = _unitOfWork.ThreadRepository.Get(x => x.Username == username)
                        .OrderByDescending(x => x.SubmittedOn)
                        .Skip(size).Take(size > Constants.BlocksizeUserSpecificThreads ? size - (size - Constants.BlocksizeUserSpecificThreads) : size)
                        .ToList();

            return Json(posts, JsonRequestBehavior.AllowGet);

        }

        public ActionResult DisplaySinglePost(int threadId)
        {
            var threadSingle = _unitOfWork.ThreadRepository.GetById(threadId);
            var comments = _unitOfWork.CommentRepository.Get(x => x.Thread_ThreadId == threadId).OrderByDescending(x => x.CommentedOn).ToList();

SkillsBook.com/SkillsBook.com/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PagedList;
using SkillsBook.Models.DAL;
using SkillsBook.Models.Models;

namespace SkillsBook.com.Controllers
{
    public class SearchController : Controller
    {
        private readonly UnitOfWork _unitOfWork = new UnitOfWork();

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public PartialViewResult SearchClassifieds(string category,string title="",string location="",string option="ALL",int page=1)
        {
            List<ClassifiedModel> searchResults = null;
            var searchQuery =
                _unitOfWork.ClassifiedRepository.Get(x => x.ClassifiedCategory.Equals(category) && x.CurrentStatus == Constants.ClassifiedItemAvailable);
            
            if (title != "" && location == "")
                searchQuery = searchQuery.Where(x => x.ClassifiedTitle.ToLower().Contains(title.ToLower()));
            if (title == "" && location != "")
                searchQuery = searchQuery.Where(x => x.City.ToLower().Contains(location.ToLower()) 
                    || x.State.ToLower().Contains(location.ToLower()) || x.Country.ToLower().Contains(location.ToLower()));
            if (title !="" && location != "")
                searchQuery = searchQuery.Where(x =>x.ClassifiedTitle.ToLower().Contains(title.ToLower())
                    && ( x.City.ToLower().Contains(location.ToLower()) 
                    || x.State.ToLower().Contains(location.ToLower()) 
                    || x.Country.ToLower().Contains(location.ToLower())));
          
            var classifiedModels = searchQuery as ClassifiedModel[] ?? searchQuery.ToArray();

            if (option == "ALL" || option == "All")
            {
                searchResults = classifiedModels.ToList();
            }
            else
            {
                searchResults = classifiedModels.Where(x=>x.ClassifiedRadio.Equals(option)).ToList();
            }
            
            int totalCount = searchResults.Count();

            ViewBag.Title = title;
            ViewBag.Location = location;
            ViewBag.Option =  option;
            return PartialView("Partial.CategorySearchResults",searchResults);
        }

        [HttpGet]
        public async Task<ActionResult> Search(string term, int page =1)
        {
            IEnumerable<ThreadModel> tagsList = null;
            int totalCount;
            if (!CacheManager.Exists("Search_"+term))
            {
                totalCount =
                    _unitOfWork.ThreadRepository.Get(x => x.Username.Contains(term) || x.Title.Contains(term) || x.Announcement.Contains(term) ).Count();
                CacheManager.AddToCache<string>("Search", totalCount, null, 5);
            }
            else
            {
                totalCount = (int) CacheManager.Get("Search_"+term);
            }

            int offset = (page - 1) * Constants.BlocksizeInitialLoad;
             try
                {
                    tagsList = _unitOfWork.ThreadRepository
                       .Get(x => x.Username.Contains(term) || x.Announcement.Contains(term) || x.Title.Contains(term))
                       .Skip((int)offset)
                       .Take(
                           (int)
                               (offset > Constants.BlocksizeInitialLoad
                                   ? offset - (offset - Constants.BlocksizeInitialLoad)
                                   : offset ==0 ? Constants.BlocksizeInitialLoad: offset));
                }
                catch (Exception ex)
                {
                    Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                }
         
                var mostLiked = CacheImplementation.GetMostLikedThreads;
                var mostViewed = CacheImplementation.GetMostViewedThreads;
                var mostResponded = CacheImplementation.GetMostCommentedThreads;
                var trendingGeneral = CacheImplementation.GetTrendingItems(Constants.TagsGeneral);
                var trendingAnnouncement = CacheImplementation.GetTrendingItems(Constants.TagsAnnouncement);
                await Task.WhenAll(mostLiked, mostViewed, mostResponded, trendingGeneral, trendingAnnouncement);
                ViewBag.MostLiked = mostLiked.Result;
                ViewBag.MostViewed = mostViewed.Result;
                ViewBag.MostResponded = mostResponded.Result;
                ViewBag.TrendingTagsGeneral = trendingGeneral.Result.Take(Constants.BlocksizeTrendingTags);
                ViewBag.TrendingTagsAnnouncement = trendingAnnouncement.Result.Take(Constants.BlocksizeTrendingTags);
                
            ViewData["SearchTerm"] = term;
            ViewData["CurrentPage"] = page;
            ViewData["TotalCount"] = totalCount;
            ViewData["TotalPages"] =  ((totalCount - 1) / Constants.BlocksizeInitialLoad) + 1;
            return !tagsList.Any() ? null : PartialView("Partial.Search",tagsList);
        }
    }
}

SkillsBook.com/SkillsBook.com/Views/Search/Index.cshtml
@using System.ComponentModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- MAIN CONTENT -->
<div class="pg-opt">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2>Search</h2>
            </div>

        </div>
    </div>
</div>

<section class="slice bg-white">
    <div class="container">
        <div class="wp-block default user-form">
            <div class="form-body">
                <fieldset class="no-padding">
                    <section>
                        <div class="row">
                            <div class="col-md-8">
                                <label for="">Search By Username/Title/Announcement</label>
                                <div class="input-group">
                                    <input type="text" name="Username" id="term_search" placeholder="Username/Title/Announcement" class="form-control left">
                                    <span class="input-group-btn">
                                        <button class="btn btn-base" type="button" id="btnGo1">Go</button>
                                    </span>
                                     
                                </div>
                            </div>
                           
                        </div>
                    </section>
                </fieldset>
                <input type ="hidden" data-url="@Url.Action("Search","Search")" id="urlSearch1"/>
                <input type="hidden" data-ajaxloader='@Url.Content("~/images/slider/fs-spinner.gif")' id="ajaxloader" />
            </div>
        </div>
        <section>
            <div id="searchResults">
            </div>
        </section>
    </div>
</section>

SkillsBook.com/SkillsBook.com/Views/Search/Partial.CategorySearchResults.cshtml
@model IEnumerable<SkillsBook.Models.Models.ClassifiedModel>
<section class="slice bg-white bb">
    <div class="wp-section shop">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="well">
                        <h4>Listing all ( @ViewBag.Title @ViewBag.Location @ViewBag.Option ) items</h4>
                    </div>
                    <div class="row" style="float:right">
                        <div class="col-md-12">
                            <ul class="pagination pagination-sm">
                                @for (var i = 1; i <= Convert.ToInt32(ViewData["TotalPages"]); i++)
                                {
                                    if (Convert.ToInt32(ViewData["CurrentPage"]) == i)
                                    {
                                        if (i < 1)
                                        {
                                            continue;
                                        }
                                        <li class="active"><a href="javascript:void(0)">@i</a></li>
                                    }
                                    else
                                    {
                                        <li><a href="javascript:void(0)" id="@i"></a></li>
                                    }
                                }
                            </ul>
                        </div>
                    </div>
                    <table class="table table-cart table-responsive">
                        <thead>
                            <tr>
                                <th>Last Updated<span> &#x25BC</span></th>
                                <th>Title</th>
                                <th>Available Or Wanted</th>
                                <th>Current Status</th>
                                <th>Location</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @item.LastUpdated.ToShortDateString()<br />
                                    </td>
                                    <td><a href='@Url.Action("DisplayClassified", "Page",new{classifiedId = @item.ClassifiedId})' style="color:cornflowerblue"><strong>@item.ClassifiedTitle</strong></a></td>
                                    <td>@item.ClassifiedRadio.ToUpperInvariant()</td>
                                    <td>@(item.CurrentStatus == 1 ? "Still Active" : "Taken")</td>
                                    <td>@item.City @item.State</td>
                                </tr>
                            }

                        </tbody>
                    </table>
                    <div class="row" style="float:right">
                        <div class="col-md-12">
                            <ul class="pagination pagination-sm">
                                @for (var i = 1; i <= Convert.ToInt32(ViewData["TotalPages"]); i++)
                                {
                                    if (Convert.ToInt32(ViewData["CurrentPage"]) == i)
                                    {
                                        if (i < 1)
                                        {
                                            continue;
                                        }
                                        <li class="active"><a href="javascript:void(0)">@i</a></li>
                                    }
                                    else
                                    {
                                        <li><a href="javascript:void(0)" id="@i"> </a></li>
                                    }
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

SkillsBook.com/SkillsBook.com/Views/Search/Partial.Search.cshtml
@model IEnumerable<SkillsBook.Models.Models.ThreadModel>
<script src='@Url.Content("~/Scripts/app/main.js")'></script>
<script src='@Url.Content("~/Scripts/app/search.js")'></script>

<div class="wp-section">
    <div class="container">
        <div class="row">
            <div id="resultpage">
                <div class="col-lg-9">
                    <ul>
                        <li>Search Results For: @ViewData["SearchTerm"]</li>
                        <li>Total Results: @ViewData["TotalCount"]</li>
                    </ul>
                    <ul class="pagination pagination-style-2">
                        @for (var i = 1; i <= Convert.ToInt32(ViewData["TotalPages"]); i++)
                        {
                            if (Convert.ToInt32(ViewData["CurrentPage"]) == i)
                            {
                                if (i < 1)
                                {
                                    continue;
                                }
                                <li class="active"><a href="javascript:void(0)">@i</a></li>
                            }
                            else
                            {
                                <li><a href="javascript:void(0)" id="@i">@i</a></li>
                            }
                        }
                    </ul>
                    <ul>
                        @Html.Partial("Partial.ThreadModelResults")
                    </ul>
                </div>

                <div class="col-md-3">
                    @Html.Partial("Partial.Accordians")
                </div>
            </div>
        </div>
    </div>
</div>